version: '3'
services:
  front:
    build: ./front
    container_name: front
    volumes:
      - ./front:/app
    ports:
      - "3000:3000"
    working_dir: "/app/react-app"
    command: "npm run start"
    tty: true
    stdin_open: true
    networks:
      backend:

  backend:
    build: ./backend
    container_name: backend
    working_dir: "/app"
    command: npm run dev
    volumes:
      - ./backend:/app
    ports:
      - "3001:3000"
    tty: true
    stdin_open: true
    networks:
      backend:
  
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: react
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      backend:

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - 3080:80
    networks:
      backend:
  
networks:
  backend:

